allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: false
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.3'
  - '@tanstack/react-query@5.101.3'
  - recharts@3.10.0
