export interface Currency {
  code: string;
  name: string;
  symbol: string;
  flag: string;
}

export const CURRENCIES: Currency[] = [
  // ── Major ──────────────────────────────────────────────────────────────────
  { code: 'USD', name: 'US Dollar',                  symbol: '$',    flag: '🇺🇸' },
  { code: 'EUR', name: 'Euro',                        symbol: '€',    flag: '🇪🇺' },
  { code: 'GBP', name: 'British Pound',               symbol: '£',    flag: '🇬🇧' },
  { code: 'JPY', name: 'Japanese Yen',                symbol: '¥',    flag: '🇯🇵' },
  { code: 'CHF', name: 'Swiss Franc',                 symbol: 'Fr',   flag: '🇨🇭' },
  { code: 'CNY', name: 'Chinese Yuan',                symbol: '¥',    flag: '🇨🇳' },

  // ── Asia-Pacific ───────────────────────────────────────────────────────────
  { code: 'AUD', name: 'Australian Dollar',           symbol: 'A$',   flag: '🇦🇺' },
  { code: 'NZD', name: 'New Zealand Dollar',          symbol: 'NZ$',  flag: '🇳🇿' },
  { code: 'SGD', name: 'Singapore Dollar',            symbol: 'S$',   flag: '🇸🇬' },
  { code: 'HKD', name: 'Hong Kong Dollar',            symbol: 'HK$',  flag: '🇭🇰' },
  { code: 'MYR', name: 'Malaysian Ringgit',           symbol: 'RM',   flag: '🇲🇾' },
  { code: 'IDR', name: 'Indonesian Rupiah',           symbol: 'Rp',   flag: '🇮🇩' },
  { code: 'THB', name: 'Thai Baht',                   symbol: '฿',    flag: '🇹🇭' },
  { code: 'PHP', name: 'Philippine Peso',             symbol: '₱',    flag: '🇵🇭' },
  { code: 'KRW', name: 'South Korean Won',            symbol: '₩',    flag: '🇰🇷' },
  { code: 'TWD', name: 'Taiwan Dollar',               symbol: 'NT$',  flag: '🇹🇼' },
  { code: 'VND', name: 'Vietnamese Dong',             symbol: '₫',    flag: '🇻🇳' },
  { code: 'INR', name: 'Indian Rupee',                symbol: '₹',    flag: '🇮🇳' },
  { code: 'BDT', name: 'Bangladeshi Taka',            symbol: '৳',    flag: '🇧🇩' },
  { code: 'PKR', name: 'Pakistani Rupee',             symbol: '₨',    flag: '🇵🇰' },
  { code: 'LKR', name: 'Sri Lankan Rupee',            symbol: 'Rs',   flag: '🇱🇰' },
  { code: 'NPR', name: 'Nepalese Rupee',              symbol: '₨',    flag: '🇳🇵' },
  { code: 'MMK', name: 'Myanmar Kyat',                symbol: 'K',    flag: '🇲🇲' },
  { code: 'KHR', name: 'Cambodian Riel',              symbol: '៛',    flag: '🇰🇭' },
  { code: 'LAK', name: 'Lao Kip',                     symbol: '₭',    flag: '🇱🇦' },
  { code: 'MNT', name: 'Mongolian Tugrik',            symbol: '₮',    flag: '🇲🇳' },
  { code: 'MOP', name: 'Macanese Pataca',             symbol: 'P',    flag: '🇲🇴' },
  { code: 'BTN', name: 'Bhutanese Ngultrum',          symbol: 'Nu',   flag: '🇧🇹' },
  { code: 'MVR', name: 'Maldivian Rufiyaa',           symbol: 'Rf',   flag: '🇲🇻' },
  { code: 'BND', name: 'Brunei Dollar',               symbol: 'B$',   flag: '🇧🇳' },
  { code: 'PGK', name: 'Papua New Guinean Kina',      symbol: 'K',    flag: '🇵🇬' },
  { code: 'FJD', name: 'Fijian Dollar',               symbol: 'FJ$',  flag: '🇫🇯' },
  { code: 'VUV', name: 'Vanuatu Vatu',                symbol: 'Vt',   flag: '🇻🇺' },
  { code: 'WST', name: 'Samoan Tālā',                 symbol: 'T',    flag: '🇼🇸' },
  { code: 'TOP', name: 'Tongan Paʻanga',              symbol: 'T$',   flag: '🇹🇴' },
  { code: 'SBD', name: 'Solomon Islands Dollar',      symbol: 'SI$',  flag: '🇸🇧' },

  // ── Middle East ────────────────────────────────────────────────────────────
  { code: 'AED', name: 'UAE Dirham',                  symbol: 'د.إ',  flag: '🇦🇪' },
  { code: 'SAR', name: 'Saudi Riyal',                 symbol: 'SR',   flag: '🇸🇦' },
  { code: 'QAR', name: 'Qatari Riyal',                symbol: 'QR',   flag: '🇶🇦' },
  { code: 'KWD', name: 'Kuwaiti Dinar',               symbol: 'KD',   flag: '🇰🇼' },
  { code: 'BHD', name: 'Bahraini Dinar',              symbol: 'BD',   flag: '🇧🇭' },
  { code: 'OMR', name: 'Omani Rial',                  symbol: 'ر.ع', flag: '🇴🇲' },
  { code: 'JOD', name: 'Jordanian Dinar',             symbol: 'JD',   flag: '🇯🇴' },
  { code: 'ILS', name: 'Israeli Shekel',              symbol: '₪',    flag: '🇮🇱' },
  { code: 'IQD', name: 'Iraqi Dinar',                 symbol: 'ع.د', flag: '🇮🇶' },
  { code: 'IRR', name: 'Iranian Rial',                symbol: '﷼',    flag: '🇮🇷' },
  { code: 'LBP', name: 'Lebanese Pound',              symbol: '£',    flag: '🇱🇧' },
  { code: 'SYP', name: 'Syrian Pound',                symbol: '£',    flag: '🇸🇾' },
  { code: 'YER', name: 'Yemeni Rial',                 symbol: '﷼',    flag: '🇾🇪' },

  // ── Europe (non-Euro) ──────────────────────────────────────────────────────
  { code: 'TRY', name: 'Turkish Lira',                symbol: '₺',    flag: '🇹🇷' },
  { code: 'SEK', name: 'Swedish Krona',               symbol: 'kr',   flag: '🇸🇪' },
  { code: 'NOK', name: 'Norwegian Krone',              symbol: 'kr',   flag: '🇳🇴' },
  { code: 'DKK', name: 'Danish Krone',                symbol: 'kr',   flag: '🇩🇰' },
  { code: 'PLN', name: 'Polish Zloty',                symbol: 'zł',   flag: '🇵🇱' },
  { code: 'CZK', name: 'Czech Koruna',                symbol: 'Kč',   flag: '🇨🇿' },
  { code: 'HUF', name: 'Hungarian Forint',            symbol: 'Ft',   flag: '🇭🇺' },
  { code: 'RON', name: 'Romanian Leu',                symbol: 'lei',  flag: '🇷🇴' },
  { code: 'BGN', name: 'Bulgarian Lev',               symbol: 'лв',   flag: '🇧🇬' },
  { code: 'ISK', name: 'Icelandic Króna',             symbol: 'kr',   flag: '🇮🇸' },
  { code: 'HRK', name: 'Croatian Kuna',               symbol: 'kn',   flag: '🇭🇷' },
  { code: 'RSD', name: 'Serbian Dinar',               symbol: 'din',  flag: '🇷🇸' },
  { code: 'UAH', name: 'Ukrainian Hryvnia',           symbol: '₴',    flag: '🇺🇦' },
  { code: 'GEL', name: 'Georgian Lari',               symbol: '₾',    flag: '🇬🇪' },
  { code: 'AMD', name: 'Armenian Dram',               symbol: '֏',    flag: '🇦🇲' },
  { code: 'AZN', name: 'Azerbaijani Manat',           symbol: '₼',    flag: '🇦🇿' },
  { code: 'KZT', name: 'Kazakhstani Tenge',           symbol: '₸',    flag: '🇰🇿' },
  { code: 'UZS', name: 'Uzbekistani Som',             symbol: 'сўм',  flag: '🇺🇿' },
  { code: 'KGS', name: 'Kyrgystani Som',              symbol: 'с',    flag: '🇰🇬' },
  { code: 'TJS', name: 'Tajikistani Somoni',          symbol: 'SM',   flag: '🇹🇯' },
  { code: 'TMT', name: 'Turkmenistani Manat',         symbol: 'T',    flag: '🇹🇲' },
  { code: 'RUB', name: 'Russian Ruble',               symbol: '₽',    flag: '🇷🇺' },
  { code: 'BYN', name: 'Belarusian Ruble',            symbol: 'Br',   flag: '🇧🇾' },
  { code: 'MDL', name: 'Moldovan Leu',                symbol: 'L',    flag: '🇲🇩' },
  { code: 'MKD', name: 'Macedonian Denar',            symbol: 'ден',  flag: '🇲🇰' },
  { code: 'ALL', name: 'Albanian Lek',                symbol: 'L',    flag: '🇦🇱' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Mark',     symbol: 'KM',   flag: '🇧🇦' },

  // ── Americas ───────────────────────────────────────────────────────────────
  { code: 'CAD', name: 'Canadian Dollar',             symbol: 'C$',   flag: '🇨🇦' },
  { code: 'MXN', name: 'Mexican Peso',                symbol: '$',    flag: '🇲🇽' },
  { code: 'BRL', name: 'Brazilian Real',              symbol: 'R$',   flag: '🇧🇷' },
  { code: 'ARS', name: 'Argentine Peso',              symbol: '$',    flag: '🇦🇷' },
  { code: 'CLP', name: 'Chilean Peso',                symbol: '$',    flag: '🇨🇱' },
  { code: 'COP', name: 'Colombian Peso',              symbol: '$',    flag: '🇨🇴' },
  { code: 'PEN', name: 'Peruvian Sol',                symbol: 'S/',   flag: '🇵🇪' },
  { code: 'UYU', name: 'Uruguayan Peso',              symbol: '$U',   flag: '🇺🇾' },
  { code: 'PYG', name: 'Paraguayan Guaraní',          symbol: '₲',    flag: '🇵🇾' },
  { code: 'BOB', name: 'Bolivian Boliviano',          symbol: 'Bs',   flag: '🇧🇴' },
  { code: 'VES', name: 'Venezuelan Bolívar',          symbol: 'Bs.S', flag: '🇻🇪' },
  { code: 'DOP', name: 'Dominican Peso',              symbol: 'RD$',  flag: '🇩🇴' },
  { code: 'GTQ', name: 'Guatemalan Quetzal',          symbol: 'Q',    flag: '🇬🇹' },
  { code: 'CRC', name: 'Costa Rican Colón',           symbol: '₡',    flag: '🇨🇷' },
  { code: 'HNL', name: 'Honduran Lempira',            symbol: 'L',    flag: '🇭🇳' },
  { code: 'NIO', name: 'Nicaraguan Córdoba',          symbol: 'C$',   flag: '🇳🇮' },
  { code: 'PAB', name: 'Panamanian Balboa',           symbol: 'B/.',  flag: '🇵🇦' },
  { code: 'CUP', name: 'Cuban Peso',                  symbol: '$',    flag: '🇨🇺' },
  { code: 'TTD', name: 'Trinidad Dollar',             symbol: 'TT$',  flag: '🇹🇹' },
  { code: 'JMD', name: 'Jamaican Dollar',             symbol: 'J$',   flag: '🇯🇲' },
  { code: 'BBD', name: 'Barbadian Dollar',            symbol: 'Bds$', flag: '🇧🇧' },
  { code: 'BZD', name: 'Belize Dollar',               symbol: 'BZ$',  flag: '🇧🇿' },
  { code: 'GYD', name: 'Guyanese Dollar',             symbol: '$',    flag: '🇬🇾' },
  { code: 'SRD', name: 'Surinamese Dollar',           symbol: '$',    flag: '🇸🇷' },
  { code: 'AWG', name: 'Aruban Florin',               symbol: 'ƒ',    flag: '🇦🇼' },
  { code: 'ANG', name: 'Neth. Antillean Guilder',     symbol: 'ƒ',    flag: '🇨🇼' },
  { code: 'BSD', name: 'Bahamian Dollar',             symbol: 'B$',   flag: '🇧🇸' },
  { code: 'KYD', name: 'Cayman Islands Dollar',       symbol: 'CI$',  flag: '🇰🇾' },
  { code: 'XCD', name: 'East Caribbean Dollar',       symbol: '$',    flag: '🇦🇬' },
  { code: 'HTG', name: 'Haitian Gourde',              symbol: 'G',    flag: '🇭🇹' },

  // ── Africa ─────────────────────────────────────────────────────────────────
  { code: 'ZAR', name: 'South African Rand',          symbol: 'R',    flag: '🇿🇦' },
  { code: 'NGN', name: 'Nigerian Naira',              symbol: '₦',    flag: '🇳🇬' },
  { code: 'KES', name: 'Kenyan Shilling',             symbol: 'KSh',  flag: '🇰🇪' },
  { code: 'GHS', name: 'Ghanaian Cedi',               symbol: '₵',    flag: '🇬🇭' },
  { code: 'EGP', name: 'Egyptian Pound',              symbol: '£',    flag: '🇪🇬' },
  { code: 'MAD', name: 'Moroccan Dirham',             symbol: 'MAD',  flag: '🇲🇦' },
  { code: 'DZD', name: 'Algerian Dinar',              symbol: 'دج',   flag: '🇩🇿' },
  { code: 'TND', name: 'Tunisian Dinar',              symbol: 'DT',   flag: '🇹🇳' },
  { code: 'LYD', name: 'Libyan Dinar',                symbol: 'LD',   flag: '🇱🇾' },
  { code: 'TZS', name: 'Tanzanian Shilling',          symbol: 'TSh',  flag: '🇹🇿' },
  { code: 'UGX', name: 'Ugandan Shilling',            symbol: 'USh',  flag: '🇺🇬' },
  { code: 'ETB', name: 'Ethiopian Birr',              symbol: 'Br',   flag: '🇪🇹' },
  { code: 'XAF', name: 'CFA Franc BEAC',              symbol: 'Fr',   flag: '🇨🇲' },
  { code: 'XOF', name: 'CFA Franc BCEAO',             symbol: 'Fr',   flag: '🇸🇳' },
  { code: 'ZMW', name: 'Zambian Kwacha',              symbol: 'ZK',   flag: '🇿🇲' },
  { code: 'MUR', name: 'Mauritian Rupee',             symbol: '₨',    flag: '🇲🇺' },
  { code: 'RWF', name: 'Rwandan Franc',               symbol: 'Fr',   flag: '🇷🇼' },
  { code: 'MZN', name: 'Mozambican Metical',          symbol: 'MT',   flag: '🇲🇿' },
  { code: 'MGA', name: 'Malagasy Ariary',             symbol: 'Ar',   flag: '🇲🇬' },
  { code: 'BWP', name: 'Botswanan Pula',              symbol: 'P',    flag: '🇧🇼' },
  { code: 'NAD', name: 'Namibian Dollar',             symbol: 'N$',   flag: '🇳🇦' },
  { code: 'MWK', name: 'Malawian Kwacha',             symbol: 'MK',   flag: '🇲🇼' },
  { code: 'SCR', name: 'Seychellois Rupee',           symbol: '₨',    flag: '🇸🇨' },
  { code: 'GMD', name: 'Gambian Dalasi',              symbol: 'D',    flag: '🇬🇲' },
  { code: 'GNF', name: 'Guinean Franc',               symbol: 'Fr',   flag: '🇬🇳' },
  { code: 'BIF', name: 'Burundian Franc',             symbol: 'Fr',   flag: '🇧🇮' },
  { code: 'DJF', name: 'Djiboutian Franc',            symbol: 'Fr',   flag: '🇩🇯' },
  { code: 'KMF', name: 'Comorian Franc',              symbol: 'Fr',   flag: '🇰🇲' },
  { code: 'SLE', name: 'Sierra Leonean Leone',        symbol: 'Le',   flag: '🇸🇱' },
  { code: 'SOS', name: 'Somali Shilling',             symbol: 'Sh',   flag: '🇸🇴' },
  { code: 'SDG', name: 'Sudanese Pound',              symbol: '£',    flag: '🇸🇩' },
  { code: 'SSP', name: 'South Sudanese Pound',        symbol: '£',    flag: '🇸🇸' },
  { code: 'SZL', name: 'Swazi Lilangeni',             symbol: 'L',    flag: '🇸🇿' },
  { code: 'LSL', name: 'Lesotho Loti',                symbol: 'L',    flag: '🇱🇸' },
  { code: 'LRD', name: 'Liberian Dollar',             symbol: '$',    flag: '🇱🇷' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra',   symbol: 'Db',   flag: '🇸🇹' },
  { code: 'AOA', name: 'Angolan Kwanza',              symbol: 'Kz',   flag: '🇦🇴' },
  { code: 'CDF', name: 'Congolese Franc',             symbol: 'Fr',   flag: '🇨🇩' },
  { code: 'CVE', name: 'Cape Verdean Escudo',         symbol: '$',    flag: '🇨🇻' },
  { code: 'ERN', name: 'Eritrean Nakfa',              symbol: 'Nfk',  flag: '🇪🇷' },
  { code: 'XPF', name: 'CFP Franc',                   symbol: 'Fr',   flag: '🇵🇫' },
  { code: 'MRU', name: 'Mauritanian Ouguiya',         symbol: 'UM',   flag: '🇲🇷' },
  { code: 'SHP', name: 'Saint Helena Pound',          symbol: '£',    flag: '🇸🇭' },
  { code: 'FKP', name: 'Falkland Islands Pound',      symbol: '£',    flag: '🇫🇰' },
  { code: 'GIP', name: 'Gibraltar Pound',             symbol: '£',    flag: '🇬🇮' },
  { code: 'BMD', name: 'Bermudian Dollar',            symbol: '$',    flag: '🇧🇲' },
  { code: 'ZWG', name: 'Zimbabwe Gold',               symbol: 'ZiG',  flag: '🇿🇼' },
  { code: 'AFN', name: 'Afghan Afghani',              symbol: '؋',    flag: '🇦🇫' },
];

export const getCurrency = (code: string): Currency | undefined =>
  CURRENCIES.find((c) => c.code === code);

export const POPULAR_CONVERSIONS = [
  { from: 'JPY', to: 'MYR' },
  { from: 'USD', to: 'MYR' },
  { from: 'MYR', to: 'USD' },
  { from: 'EUR', to: 'USD' },
  { from: 'SGD', to: 'MYR' },
  { from: 'USD', to: 'EUR' },
  { from: 'GBP', to: 'USD' },
  { from: 'USD', to: 'JPY' },
];

export const MULTI_CURRENCY_TARGETS = [
  'USD', 'EUR', 'GBP', 'MYR', 'SGD', 'AUD', 'CAD', 'CHF', 'HKD', 'INR',
];
