// Worker entry point. OpenNext generates the fetch handler; this wraps it so the same
// Worker can also export the AlertStore Durable Object and run the alerts cron.
// See https://opennext.js.org/cloudflare/howtos/custom-worker

// oxlint-disable-next-line typescript/ban-ts-comment -- generated by `opennextjs-cloudflare build`, absent before it runs
// @ts-ignore
import { default as handler } from '../.open-next/worker.js';

export { AlertStore } from './alert-store';

export default {
  fetch: handler.fetch,

  async scheduled(_controller, env, ctx) {
    const store = env.ALERTS.get(env.ALERTS.idFromName('global'));
    ctx.waitUntil(store.check().then((summary) => console.log('Rate alert check', summary)));
  },
} satisfies ExportedHandler<Env>;
